
def emit_header(outfile):
    outfile.write("import csv\n")
    outfile.write("\n")
    outfile.write("def isfloat(element):\n")
    outfile.write("\ttry:\n")
    outfile.write("\t\tfloat(element)\n")
    outfile.write("\t\treturn True\n")
    outfile.write("\texcept ValueError:\n")
    outfile.write("\t\treturn False\n")
    outfile.write("def isint(element):\n")
    outfile.write("\ttry:\n")
    outfile.write("\t\tint(element)\n")
    outfile.write("\t\treturn True\n")
    outfile.write("\texcept ValueError:\n")
    outfile.write("\t\treturn False    \n")
    outfile.write("def get_value(v):\n")
    outfile.write("\tif isint(v):\n")
    outfile.write("\t\treturn int(v)\n")
    outfile.write("\telif isfloat(v):\n")
    outfile.write("\t\treturn float(v)\n")
    outfile.write("\telse:\n")
    outfile.write("\t\treturn str(v)\n")

def emit_footer(outfile,r):
    outfile.write("if __name__ == \"__main__\":\n")
    func="operator_"+str(r.id)
    outfile.write("\tfor r in "+func+"():\n")
    outfile.write("\t\tprint (r)\n")